name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^10.1.0
  animated_splash_screen: ^1.2.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.3.3
  shared_preferences: ^2.0.15
  get: ^4.6.5


  # state management
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/
